# -*- coding: utf-8 -*-
"""consumidor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRhl8QbXZMWihywkJdX6mttgC0jZzGJn

# Consumer
"""

from kafka import KafkaConsumer
from collections import Counter
import pandas as pd
import threading
import time
import uuid

# Generar un group_id único
group_id = str(uuid.uuid4())

# Configurar el consumidor de Kafka
consumer = KafkaConsumer(
    'mi-topico-libros',
    bootstrap_servers=['localhost:9092'],
    auto_offset_reset='earliest',
    enable_auto_commit=True,
    group_id=group_id
)

generos_leidos = []

# Función para consumir mensajes
def consume_messages():
    print("Esperando mensajes...")
    for message in consumer:
        libro = message.value.decode('utf-8')
        print(f"Mensaje recibido: {libro}")  # Ver el mensaje recibido

        # Verificar si el mensaje tiene el formato esperado
        partes = libro.split(" - ")
        if len(partes) < 2:
            print(f"Mensaje recibido no válido: {libro}")
            continue  # Saltar a la siguiente iteración si el mensaje es inválido

        genero = partes[1]  # Extraer el género del mensaje
        generos_leidos.append(genero)

# Función para mostrar una tabla de frecuencias
def mostrar_tabla_frecuencias():
    while True:
        if generos_leidos:
            counter = Counter(generos_leidos)
            top_generos = counter.most_common(5)  # Los 5 géneros más mencionados
            df = pd.DataFrame(top_generos, columns=['Género', 'Cantidad'])
            print("\nGéneros más mencionados:")
            print(df)
        time.sleep(5)

# Crear hilos para consumir y mostrar mensajes
threading.Thread(target=consume_messages, daemon=True).start()
threading.Thread(target=mostrar_tabla_frecuencias, daemon=True).start()

# Mantener el script corriendo
while True:
    time.sleep(1)