# -*- coding: utf-8 -*-
"""productor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pqx6k1xLiGYNHVml0gBX8XFHrxmGMQG

# Productor
"""

from kafka import KafkaProducer
from faker import Faker
import time
import random

# Instanciar Faker
fake = Faker()

# Lista de géneros literarios
generos = ["Ficción", "No Ficción", "Ciencia Ficción", "Fantasía", "Misterio", "Romance", "Biografía"]

# Configurar el productor de Kafka
producer = KafkaProducer(
    bootstrap_servers=['localhost:9092'],
    value_serializer=lambda v: v.encode('utf-8')  # Serializar a utf-8
)

# Bucle para enviar mensajes al tópico
while True:
    titulo_libro = fake.catch_phrase()  # Generar un título aleatorio
    genero_libro = random.choice(generos)  # Elegir un género aleatorio
    mensaje = f"{titulo_libro} - {genero_libro}"
    producer.send("mi-topico-libros", value=mensaje)
    print(f"Mensaje enviado: {mensaje}")
    time.sleep(1)  # Pausa de 1 segundo entre mensajes

producer.flush()
producer.close()

